User 1000
Group 1000
Port 8888
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogLevel Info
Allow 0.0.0.0/0
Allow ::/0
ViaProxyName "tinyproxy"
