name: Release

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:
        inputs:
            version:
                description: "Tinyproxy version"
                required: false
                type: string
            force:
                description: "Force release"
                required: false
                type: boolean
                default: true

permissions:
    contents: read
    packages: write

env:
    IMAGE_NAME: ""
    LOCAL_IMAGE_NAME: ""
    TINYPROXY_VERSION: ${{ github.event.inputs.version }}
    NEEDS_RELEASE: ${{ github.event.inputs.force }}

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - run: |
                find . -type f -name "*.sh" -exec chmod +x {} \;

            - name: Fetch release information
              env:
                  GH_TOKEN: ${{ github.token }}
                  FORCE: ${{ github.event.inputs.force }}
              run: |
                  ROOT_DIR="$(pwd)"
                  . "./_utils.sh"
                  echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
                  echo "LOCAL_IMAGE_NAME=$LOCAL_IMAGE_NAME" >> $GITHUB_ENV
                  "./release-info.sh"
                  echo "TINYPROXY_VERSION=$(cat ./dist/version.txt)" >> $GITHUB_ENV
                  echo "NEEDS_RELEASE=$(cat ./dist/needs_release.txt)" >> $GITHUB_ENV

            - name: Build image
              if: ${{ env.NEEDS_RELEASE == 'true' }}
              env:
                  GH_TOKEN: ${{ github.token }}
              run: ./build.sh

            - name: Login to GHCR
              uses: redhat-actions/podman-login@v1
              if: ${{ env.NEEDS_RELEASE == 'true' }}
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ github.token }}

            - name: Publish image to GHCR
              if: ${{ env.NEEDS_RELEASE == 'true' }}
              run: |
                  podman manifest push --all ${{ env.LOCAL_IMAGE_NAME }}:${{ env.TINYPROXY_VERSION }} ${{ env.IMAGE_NAME }}:${{ env.TINYPROXY_VERSION }}
                  podman manifest push --all ${{ env.LOCAL_IMAGE_NAME }}:${{ env.TINYPROXY_VERSION }} ${{ env.IMAGE_NAME }}:latest
